[package]
name = "hello-rocket"
version = "0.1.0"
edition = "2021"


[dependencies]
rocket = "0.4.2"
diesel = { version = "1.4.5", features = ["postgres"] }
dotenv = "0.15.0"
r2d2-diesel = "1.0.0"
r2d2 = "0.8.3"
serde = { version = "1.0", features = ["derive"] }

[dependencies.rocket_contrib]
version = "0.4.10"
features = ["diesel_postgres_pool"]