version: "3.9"
services:

  api:
    container_name: api
    init: true
    privileged: true 
    devices: 
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    env_file:
      - .env
    build:
        context: ./
    volumes:
      - ./:/app
      - /app/target
    ports:
      - "8080:8080"
    depends_on:
      - db
      - db_test
    entrypoint: ["/bin/bash", "./entrypoint.sh"]

  db:
    container_name: db
    image: postgres:14.2
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'api'
      PGDATA: /data/postgres
    volumes:
       - db:/data/postgres
    restart: always

  db_test:
    container_name: db_test
    image: postgres:14.2
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'api_test'
      PGDATA: /data/postgres
    volumes:
       - db_test:/data/postgres
    restart: always

volumes:
    db:
    db_test:
