name: tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: nemesiscodex/actix-todo-cache
    services:
      postgres:
        image: postgres:10.12-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: api_test
        ports:
        # will assign a random free host port
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    # - name: Update packages
    #   run: apt-get upgrade
    - uses: actions/checkout@v2
    - name: Move cache
      run: mv /cache/target .
    # - name: Update rustup
    #   run: rustup update
    - name: Run migrations
      run: diesel migration run
      env:
        DATABASE_URL: postgres://postgres:postgres@postgres/postgres
    # - name: Run tests
    #   run: cargo test --verbose
    #   env:
    #     RUST_LOG: info

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Run cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test
      env:
        DATABASE_URL_TEST: postgres://postgres:postgres@postgres/postgres
